
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:your_db_name}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none   # 개발 환경에서는 update, 운영은 validate 혹은 none
    show-sql: false

aws:
  access-key-id: ${ACCESS_KEY}
  secret-access-key:  ${SECRET_KEY}
  region: ap-northeast-2
  s3:
    bucket-name:  ${BUCKET_NAME}