#spring:
#  config:
#    import: optional:file:.env[.properties]
#  application:
#    name: day14
#  profiles:
#    active: prod
#
#
#aws:
#  access-key-id: ${ACCESS_KEY}
#  secret-access-key:  ${SECRET_KEY}
#  region: ap-northeast-2
#  s3:
#    bucket-name:  ${BUCKET_NAME}
#

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_API_KEY}
            client-secret: ${GOOGLE_OAUTH_SECRET_PW}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  google:
    maps:
      api:
        key: ${GOOGLE_MAPS_API_KEY}
