
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://dev-db.internal:5432/baemin_dev
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # 개발 환경에서는 update, 운영은 validate 혹은 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  access-key-id: ${ACCESS_KEY}
  secret-access-key:  ${SECRET_KEY}
  region: ap-northeast-2
  s3:
    bucket-name:  ${BUCKET_NAME}